export const DEFAULT_REFETCH_ON_WINDOW_FOCUS_STALE_TIME = 5000 // 1 minute

export const NEXT_PUBLIC_RESUME_URL = process.env.NEXT_PUBLIC_RESUME_URL

export const NEXT_EMAILJS_SERVICE = process.env.NEXT_EMAILJS_SERVICE
export const NEXT_EMAILJS_TEMPLATE = process.env.NEXT_EMAILJS_TEMPLATE
export const NEXT_EMAILJS_PUBLIC_KEY = process.env.NEXT_EMAILJS_PUBLIC_KEY